package io.kotest.property.arbs.travel

import io.kotest.property.Arb
import io.kotest.property.arbitrary.of

data class Airline(val name: String) {
  companion object {
    val all = listOf(
      Airline("Titan Airways"),
      Airline("Swift Air, LLC"),
      Airline("DCA"),
      Airline("JetClub AG"),
      Airline("Vision Airlines"),
      Airline("Metropix UK, LLP."),
      Airline("Open Skies"),
      Airline("Avjet Corporation"),
      Airline("Comlux Malta Ltd."),
      Airline("Unijet"),
      Airline("Air Alsie A/S"),
      Airline("PSA Airlines Inc."),
      Airline("Piedmont Airlines"),
      Airline("KaiserAir, Inc."),
      Airline("Alsek Air"),
      Airline("Jet link AG"),
      Airline("Regal Air"),
      Airline("Zeal 320"),
      Airline("Regions Air, Inc."),
      Airline("Silver Airways"),
      Airline("AeroLogic GmbH"),
      Airline("Boutique Air"),
      Airline("Olson Air Service"),
      Airline("Belize Trans Air"),
      Airline("LAN Argentina"),
      Airline("Lan Dominica"),
      Airline("Air North"),
      Airline("Warbelow"),
      Airline("Bellair Inc."),
      Airline("Aerolitoral"),
      Airline("Queen Air"),
      Airline("Aerosur"),
      Airline("Atlas Air Inc."),
      Airline("Aviacsa Airlines"),
      Airline("Israir Airlines"),
      Airline("Air Ukraine"),
      Airline("Krasair"),
      Airline("Jeju Air Co Ltd."),
      Airline("First Air"),
      Airline("MK Airlines Ltd."),
      Airline("Era Aviation"),
      Airline("Lb Limited"),
      Airline("Servant Air Inc."),
      Airline("Bering Air Inc."),
      Airline("Wilburs Inc."),
      Airline("Jetall Airways"),
      Airline("Edelweiss Air Ag"),
      Airline("Endeavor Air Inc."),
      Airline("Cape Air"),
      Airline("Colgan Air"),
      Airline("Southern Air Inc."),
      Airline("Cielos De Peru"),
      Airline("Air Comet S.A."),
      Airline("Air 21"),
      Airline("AAA Airlines"),
      Airline("Audi Air Inc."),
      Airline("Air Sunshine Inc."),
      Airline("Alpine Air"),
      Airline("Air Bahia"),
      Airline("ABX Air, Inc."),
      Airline("Air Canada"),
      Airline("Academy Airlines"),
      Airline("Air Central Inc."),
      Airline("Check-Air Inc."),
      Airline("Alliance Airlines"),
      Airline("Antonov Company"),
      Airline("Aero Freight"),
      Airline("Aero Coach"),
      Airline("Air Caravane Inc."),
      Airline("Argo S. A."),
      Airline("Air Alpha"),
      Airline("Air Hawaii"),
      Airline("Air National"),
      Airline("All Island Air"),
      Airline("Air Caribbean"),
      Airline("Air Express Inc."),
      Airline("Airgo Inc."),
      Airline("Air Mont. Inc."),
      Airline("Air Indiana"),
      Airline("Norontair"),
      Airline("Alliance Air"),
      Airline("Aerodynamics Inc."),
      Airline("Skyway Airlines"),
      Airline("Allied Airlines"),
      Airline("Brandt Air"),
      Airline("Air Link Airways"),
      Airline("Air L.A."),
      Airline("Altus Airlines"),
      Airline("Aleutian Air"),
      Airline("Atlanta Express"),
      Airline("Aeromexico"),
      Airline("Americair Inc."),
      Airline("AvAir"),
      Airline("Air Nebraska Inc."),
      Airline("Atlantic Air"),
      Airline("Air North/Nenana"),
      Airline("Trans New York"),
      Airline("Action Airlines"),
      Airline("Aerovias S.A."),
      Airline("Air New Orleans"),
      Airline("Air Cape"),
      Airline("Alpha Air"),
      Airline("Air Spirit Inc."),
      Airline("Arnold Aviation"),
      Airline("Air Oregon"),
      Airline("Air Sedona"),
      Airline("Arizona Airways"),
      Airline("Air South Inc."),
      Airline("Amistad Airlines"),
      Airline("Air South"),
      Airline("Air Casino"),
      Airline("Asap Air Inc."),
      Airline("Aerosur (1)"),
      Airline("Astor Air"),
      Airline("Astro Airways"),
      Airline("Air South (1)"),
      Airline("Royal Air Maroc"),
      Airline("Air Southeast"),
      Airline("Aerotransit Inc."),
      Airline("Air Carolina"),
      Airline("Av Center Inc."),
      Airline("Airvantage"),
      Airline("Aviation Sales"),
      Airline("Air Vermont Inc."),
      Airline("Aviation Services"),
      Airline("Air West Airlines"),
      Airline("Finnair Oy"),
      Airline("JetBlue Airways"),
      Airline("Bankair Inc."),
      Airline("Bard-Air Corp."),
      Airline("Balair Ag"),
      Airline("Jet Express"),
      Airline("Air Belgium"),
      Airline("Beyer Aviation"),
      Airline("Markair Inc."),
      Airline("Million Air"),
      Airline("Big Island Air"),
      Airline("Air Bvi Limited"),
      Airline("Braniff Inc."),
      Airline("Boise Air Service"),
      Airline("Aeromar C. Por A."),
      Airline("Barrow Air"),
      Airline("Blue Bell Inc."),
      Airline("Spantax S. A."),
      Airline("Bay Air"),
      Airline("Abaco Air, Ltd."),
      Airline("Canjet Airlines"),
      Airline("Air China"),
      Airline("C & M Airlines"),
      Airline("Air Virginia"),
      Airline("CAT Aviation"),
      Airline("Air One Inc."),
      Airline("Carriba Air Inc."),
      Airline("Air Atlanta Inc."),
      Airline("Cityhop"),
      Airline("Chicago Airlines"),
      Airline("Chicago Air Taxi"),
      Airline("Bemidji Airlines"),
      Airline("Chandler Flyer"),
      Airline("Charter Airlines"),
      Airline("Charter One"),
      Airline("A/S Conair"),
      Airline("Inlet Airlines"),
      Airline("Coker Aviation Inc."),
      Airline("Commutair"),
      Airline("Coral Air Inc."),
      Airline("Compass Airlines"),
      Airline("Capitol Air Lines"),
      Airline("Capitol Air"),
      Airline("Commuter Airlines"),
      Airline("Caribair"),
      Airline("Cresent Medivac"),
      Airline("Corporate Air"),
      Airline("Casino Airlines"),
      Airline("Century Airlines"),
      Airline("Cothron Aviation"),
      Airline("Chartair"),
      Airline("Caraven S.A."),
      Airline("Aviation Concepts"),
      Airline("Dan Air Services"),
      Airline("Danbury Airlines"),
      Airline("Condor Flugdienst"),
      Airline("Decatur Aviation"),
      Airline("Independence Air"),
      Airline("DHL Airlines Inc."),
      Airline("DHL Aero Expresso"),
      Airline("Northern Star"),
      Airline("Maersk Air I/S"),
      Airline("Desert Airlines"),
      Airline("Dulles Express"),
      Airline("Devoe Airlines"),
      Airline("Dawn Air"),
      Airline("Dolphin Express"),
      Airline("Execaire Aviation Ltd."),
      Airline("Eclipse Airlines"),
      Airline("Andes"),
      Airline("Ede Aire"),
      Airline("Exec Express II"),
      Airline("Exec Express"),
      Airline("Eagle Airline"),
      Airline("Eagle Jet Charter"),
      Airline("Saeta Airlines"),
      Airline("Aer Lingus Plc"),
      Airline("Emirates"),
      Airline("Air Pacific Inc."),
      Airline("Emerald Airlines"),
      Airline("Metro Express"),
      Airline("Astar USA, LLC"),
      Airline("Erie Airways Inc."),
      Airline("Evanston Aviation"),
      Airline("Rio Grande Air"),
      Airline("Executive Charter"),
      Airline("Etihad Airways"),
      Airline("Freedom Airlines Inc."),
      Airline("Tower Air Inc."),
      Airline("Icelandair"),
      Airline("Air Pacific Ltd."),
      Airline("Florida Air"),
      Airline("Flirite Inc."),
      Airline("Ford-Aire Inc."),
      Airline("Foster Aviation"),
      Airline("TAG Aviation S.A."),
      Airline("Air Aruba"),
      Airline("Freedom Air"),
      Airline("Frontier Commuter"),
      Airline("Farwest Airlines"),
      Airline("F.S. Air Service"),
      Airline("Southern Airways"),
      Airline("Skycraft Inc."),
      Airline("Skybus Inc."),
      Airline("Far West Airlines"),
      Airline("Flying Boat"),
      Airline("Aerochago S.A."),
      Airline("Allegiant Air"),
      Airline("Gulf Air Taxi"),
      Airline("G5 Executive Ag"),
      Airline("General Air Cargo"),
      Airline("Midway Commuter"),
      Airline("Gulf Air Company"),
      Airline("Gulf Flite Center"),
      Airline("Cargo 360, Inc."),
      Airline("Eurofly S.p.A"),
      Airline("Mexicargo"),
      Airline("Laker Airways"),
      Airline("Air America"),
      Airline("Air Foyle Limited"),
      Airline("GCS Air Service"),
      Airline("Aviateca"),
      Airline("Gull Air Inc."),
      Airline("Grant Aviation"),
      Airline("City Bird"),
      Airline("Magadan Airlines"),
      Airline("Hapag Lloyd Flug."),
      Airline("Homer Air"),
      Airline("Av Atlantic"),
      Airline("Helitrans"),
      Airline("Hub Express"),
      Airline("Markair Express"),
      Airline("Helitac Aviation"),
      Airline("Air Haiti S. A."),
      Airline("Haines Airways"),
      Airline("Holidair Airways"),
      Airline("Iowa Airlines"),
      Airline("Harmony Airways"),
      Airline("Business Express"),
      Airline("Heritage Airlines"),
      Airline("Tar Airlines"),
      Airline("Hyannis Aviation"),
      Airline("Iraqi Airways"),
      Airline("Iscargo Hf"),
      Airline("Meridiana S.p.A"),
      Airline("Iowa Airways"),
      Airline("Aruba Cargo"),
      Airline("Island Express"),
      Airline("Island Airlines"),
      Airline("Inair"),
      Airline("Air Chico"),
      Airline("Jer-Don Air"),
      Airline("Spanair S.A."),
      Airline("Jim Air Inc."),
      Airline("Excel Airways"),
      Airline("Jalways Co. Ltd."),
      Airline("Aero California"),
      Airline("Yugoslav Airlines"),
      Airline("Arrow Air Inc."),
      Airline("Jes Air Ltd."),
      Airline("Arizona Express"),
      Airline("Kalitta Air LLC"),
      Airline("Katmai Air"),
      Airline("Haiti Air"),
      Airline("Keene Airways"),
      Airline("Key Airlines"),
      Airline("Aloha Air Cargo"),
      Airline("Time Air Ltd."),
      Airline("Air Malta"),
      Airline("Kar-Air Oy"),
      Airline("Turks Air Ltd."),
      Airline("Crown Air"),
      Airline("Lan Colombia"),
      Airline("La Skycab Airline"),
      Airline("La Helicopter"),
      Airline("Lapsa"),
      Airline("Laredo Air"),
      Airline("Lawrence Aviation"),
      Airline("Millon Air Inc."),
      Airline("Legend Airlines"),
      Airline("Latcr"),
      Airline("Lake Coastal"),
      Airline("Le Point Air"),
      Airline("L'Express"),
      Airline("Jettrain Airlines"),
      Airline("Luxair"),
      Airline("Havasu Airlines"),
      Airline("Jin Air Co Ltd."),
      Airline("Loken Aviation"),
      Airline("Lakeland Aviation"),
      Airline("Lorair Ltd."),
      Airline("Aero Commuter"),
      Airline("Lan Peru Airlines"),
      Airline("Lacsa"),
      Airline("Air Liberte"),
      Airline("Maui Airlines"),
      Airline("Magum Airlines"),
      Airline("The Maui Commuter"),
      Airline("Maverick Airways"),
      Airline("Maxair Inc."),
      Airline("Metro Airlines"),
      Airline("Manhattan Express"),
      Airline("Metro Express 11"),
      Airline("Champion Air"),
      Airline("Mohawk Airlines"),
      Airline("Mahalo Air"),
      Airline("Aero Costa Rica"),
      Airline("Merlin Express"),
      Airline("M & N Aviation"),
      Airline("Envoy Air"),
      Airline("Egyptair"),
      Airline("Midwest Aviation"),
      Airline("Mst Aviation"),
      Airline("Aerolineas Mundo"),
      Airline("MAXjet"),
      Airline("Aero Continente"),
      Airline("National Airlines"),
      Airline("Npa Inc."),
      Airline("Nationair"),
      Airline("Nasville Eagle"),
      Airline("National Air"),
      Airline("Sterling Cargo"),
      Airline("Intair"),
      Airline("Nacnet"),
      Airline("Nevada Airlines"),
      Airline("Lanica"),
      Airline("Spirit Air Lines"),
      Airline("Norcanair"),
      Airline("Nolinor Aviation"),
      Airline("Air Japan Co"),
      Airline("Northaire"),
      Airline("Air Niugini"),
      Airline("Nevis Express"),
      Airline("New York Air Inc."),
      Airline("Air New Zealand"),
      Airline("Olympic Airways"),
      Airline("Aerocondor"),
      Airline("Air Finland Ltd."),
      Airline("Comair Inc."),
      Airline("Omaha Aviation"),
      Airline("Prestige Airways"),
      Airline("Czech Airlines"),
      Airline("Quassar De Mexico"),
      Airline("Air Nauru"),
      Airline("Sun Aire Lines"),
      Airline("Flying Boat Inc."),
      Airline("Orion Air"),
      Airline("Orion Air Inc."),
      Airline("Austrian Airlines"),
      Airline("Otter Air"),
      Airline("Aeromaritime"),
      Airline("Pro Air Inc."),
      Airline("Privatair"),
      Airline("Pacific Cal Air"),
      Airline("Pace Airlines"),
      Airline("Pacair"),
      Airline("Pem-Air Limited"),
      Airline("Air Europe S.P.A."),
      Airline("Pearson Aircraft"),
      Airline("Air Pennsylvania"),
      Airline("Pacificair"),
      Airline("Asia Pacific"),
      Airline("Phillips Airlines"),
      Airline("Phoenix Airlines"),
      Airline("Aero Peru"),
      Airline("Planes Inc."),
      Airline("Planet Airways"),
      Airline("Panama Aviation"),
      Airline("Panagra Airways"),
      Airline("Pioneer Airways"),
      Airline("Potomac Air"),
      Airline("Pompano Airways"),
      Airline("Polyot Airlines"),
      Airline("Propair"),
      Airline("Prime Air Inc."),
      Airline("Sundance Airlines"),
      Airline("Pro Air Services"),
      Airline("Aeropuma"),
      Airline("40-Mile Air"),
      Airline("Sobelair"),
      Airline("Air Florida Inc."),
      Airline("Jazz Aviation LP"),
      Airline("Royal Air"),
      Airline("Aeromexpress"),
      Airline("Reno Air Inc."),
      Airline("Qwest Commuter"),
      Airline("Horizon Air"),
      Airline("Royal-Air Ltd."),
      Airline("Pan Am Express"),
      Airline("Rader Aviation"),
      Airline("Redwing Airways"),
      Airline("Realwest Airlines"),
      Airline("Renown Aviation"),
      Airline("Varig S. A."),
      Airline("Regency Air"),
      Airline("Trump Air"),
      Airline("Rio Airways Inc."),
      Airline("Air Afrique"),
      Airline("UltrAir"),
      Airline("Reliant Airlines"),
      Airline("Ram Aviation"),
      Airline("Mytravel Airways"),
      Airline("Aero Uruguay (1)"),
      Airline("Resort Commuter"),
      Airline("Air-Serve"),
      Airline("Reeves Air"),
      Airline("Air Rovers Inc."),
      Airline("Aeromech Inc."),
      Airline("Star Air A/S"),
      Airline("Sea Air Shuttle"),
      Airline("Sajen Air Inc."),
      Airline("Sallee's Aviation"),
      Airline("Air Americana"),
      Airline("Suburban Airlines"),
      Airline("Skyjet S.A."),
      Airline("Scott Aviation"),
      Airline("Skyline Airlines"),
      Airline("XL Airways France"),
      Airline("Das Air Cargo"),
      Airline("Seaborne Aviation"),
      Airline("Jetsgo"),
      Airline("Shasta Air Inc."),
      Airline("Shavano Air Inc."),
      Airline("Premiair"),
      Airline("Scanair"),
      Airline("Sunbird Inc."),
      Airline("Sky-Jet"),
      Airline("Bas Airlines"),
      Airline("Scheduled Skyways"),
      Airline("Skytrain"),
      Airline("Slocum Air Inc."),
      Airline("Sky King Inc."),
      Airline("Salair"),
      Airline("Ccair"),
      Airline("Shawnee Airlines"),
      Airline("Mall Airways Inc."),
      Airline("Sky One Express"),
      Airline("Springdale Air"),
      Airline("Spirit Helicopter"),
      Airline("Star Aviation"),
      Airline("Southern Seaplane"),
      Airline("Air America Inc."),
      Airline("Sunshine Airlines"),
      Airline("Sunbelt"),
      Airline("Sunwest Airlines"),
      Airline("Sierra Expressway"),
      Airline("Skymaster"),
      Airline("Air Colorado"),
      Airline("Tri Air Freight"),
      Airline("USAir Shuttle"),
      Airline("Oceanair Line"),
      Airline("Venexcargo"),
      Airline("Transcarga"),
      Airline("Thorson Aviation"),
      Airline("T-Bird Air Inc."),
      Airline("Trans Air Inc."),
      Airline("Skyfreight"),
      Airline("Trans Mo Airlines"),
      Airline("Air Tahiti Nui"),
      Airline("Taca Peru"),
      Airline("Transbrasil S.A."),
      Airline("Aeromexico Travel"),
      Airline("Air Molakai"),
      Airline("Air Transat"),
      Airline("The Time Machine"),
      Airline("Turner Aire"),
      Airline("Haiti Trans Air"),
      Airline("Travelair"),
      Airline("Texas Airways"),
      Airline("Temsco Airlines"),
      Airline("UFS Inc."),
      Airline("USA 3000 Airlines"),
      Airline("Ladeco"),
      Airline("Air Manila Inc."),
      Airline("Aero Uruguay"),
      Airline("US Airways Inc."),
      Airline("Air U.S."),
      Airline("Air Europa"),
      Airline("Air Illinois Inc."),
      Airline("Iliamna Air Taxi"),
      Airline("Eagle Airlines"),
      Airline("Vacationair"),
      Airline("Pacific Express"),
      Airline("Servicios Avensa"),
      Airline("Valdez Airlines"),
      Airline("Viking Express"),
      Airline("VistaJet Limited"),
      Airline("Village Aviation"),
      Airline("Valley Airlines"),
      Airline("Virgin America"),
      Airline("Aces Airlines"),
      Airline("Mn Aviation, Inc."),
      Airline("Air East Airlines"),
      Airline("Arrow Panama"),
      Airline("Waring Air"),
      Airline("Halisa Air"),
      Airline("Wheeler Airlines"),
      Airline("Wisc Air"),
      Airline("Will's Air"),
      Airline("Williams Air Inc."),
      Airline("World Air Network"),
      Airline("Welch Aviation"),
      Airline("Wings Airways"),
      Airline("Winair Inc."),
      Airline("Island Air Hawaii"),
      Airline("Wra Inc."),
      Airline("Ward Air"),
      Airline("Westjet"),
      Airline("West Isle Air"),
      Airline("Mission Air"),
      Airline("Westates Airlines"),
      Airline("WOW Air ehf"),
      Airline("Omni Air Express"),
      Airline("Aero Union Corp"),
      Airline("Cohlmia Aviation"),
      Airline("Jet Way Inc."),
      Airline("Klondike Air Inc."),
      Airline("Flight Line Inc."),
      Airline("Pat Air"),
      Airline("Jet East Inc."),
      Airline("WTC Airlines"),
      Airline("CF Air Freight"),
      Airline("Phh Air Inc."),
      Airline("Nal Inc."),
      Airline("Air Caribbean (1)"),
      Airline("Air Train Inc."),
      Airline("Salair Inc."),
      Airline("Vladivostok Air"),
      Airline("Mesaba Airlines"),
      Airline("Aerotal"),
      Airline("Lan Ecuador"),
      Airline("Casino Express"),
      Airline("Amira Air GmbH"),
      Airline("Airpac Inc."),
      Airline("Yellow Bird Air"),
      Airline("Republic Airlines"),
      Airline("PM Air, LLC"),
      Airline("Promech"),
      Airline("Monarch Airlines"),
      Airline("Air New Mexico"),
      Airline("Affretair"),
      Airline("Key Airlines Inc."),
      Airline("Air St. Thomas"),
      Airline("Air Midwest Inc."),
      Airline("Air Georgian"),
      Airline("Airbc Ltd."),
    )
  }
}

fun Arb.Companion.airline() = Arb.of(Airline.all)
