package io.kotest.property.arbs

data class Car(val value: String) {
  companion object {
    val all = listOf(
      Car("Abarth"),
      Car("Alfa Romeo"),
      Car("Aston Martin"),
      Car("Audi"),
      Car("Bentley"),
      Car("BMW"),
      Car("Bugatti"),
      Car("Cadillac"),
      Car("Chevrolet"),
      Car("Chrysler"),
      Car("Citroën"),
      Car("Dacia"),
      Car("Daewoo"),
      Car("Daihatsu"),
      Car("Dodge"),
      Car("Donkervoort"),
      Car("DS"),
      Car("Ferrari"),
      Car("Fiat"),
      Car("Fisker"),
      Car("Ford"),
      Car("Honda"),
      Car("Hummer"),
      Car("Hyundai"),
      Car("Infiniti"),
      Car("Iveco"),
      Car("Jaguar"),
      Car("Jeep"),
      Car("Kia"),
      Car("KTM"),
      Car("Lada"),
      Car("Lamborghini"),
      Car("Lancia"),
      Car("Land Rover"),
      Car("Landwind"),
      Car("Lexus"),
      Car("Lotus"),
      Car("Maserati"),
      Car("Maybach"),
      Car("Mazda"),
      Car("McLaren"),
      Car("Mercedes-Benz"),
      Car("MG"),
      Car("Mini"),
      Car("Mitsubishi"),
      Car("Morgan"),
      Car("Nissan"),
      Car("Opel"),
      Car("Peugeot"),
      Car("Porsche"),
      Car("Renault"),
      Car("Rolls-Royce"),
      Car("Rover"),
      Car("Saab"),
      Car("Seat"),
      Car("Skoda"),
      Car("Smart"),
      Car("SsangYong"),
      Car("Subaru"),
      Car("Suzuki"),
      Car("Tesla"),
      Car("Toyota"),
      Car("Volkswagen"),
      Car("Volvo"),
    )
  }
}
