package io.kotest.property.arbs.movies

import io.kotest.property.Arb
import io.kotest.property.arbitrary.arbitrary
import io.kotest.property.arbitrary.flatMap
import io.kotest.property.arbitrary.map

data class MovieStar(val name: String) {
  companion object {
    val all = listOf(
      MovieStar("Tom Hanks"),
      MovieStar("Meryl Streep"),
      MovieStar("Denzel Washington"),
      MovieStar("Cate Blanchett"),
      MovieStar("Leonardo DiCaprio"),
      MovieStar("Viola Davis"),
      MovieStar("Robert De Niro"),
      MovieStar("Frances McDormand"),
      MovieStar("Al Pacino"),
      MovieStar("Judi Dench"),
      MovieStar("Anthony Hopkins"),
      MovieStar("Helen Mirren"),
      MovieStar("Morgan Freeman"),
      MovieStar("Tilda Swinton"),
      MovieStar("Christian Bale"),
      MovieStar("Jodie Foster"),
      MovieStar("Jack Nicholson"),
      MovieStar("Audrey Hepburn"),
      MovieStar("Marlon Brando"),
      MovieStar("Bette Davis"),
      MovieStar("Daniel Day-Lewis"),
      MovieStar("Sigourney Weaver"),
      MovieStar("Joaquin Phoenix"),
      MovieStar("Charlize Theron"),
      MovieStar("Samuel L. Jackson"),
      MovieStar("Julianne Moore"),
      MovieStar("Brad Pitt"),
      MovieStar("Nicole Kidman"),
      MovieStar("Tom Cruise"),
      MovieStar("Saoirse Ronan"),
      MovieStar("Will Smith"),
      MovieStar("Lupita Nyong'o"),
      MovieStar("Ian McKellen"),
      MovieStar("Kate Winslet"),
      MovieStar("Harrison Ford"),
      MovieStar("Naomi Watts"),
      MovieStar("Edward Norton"),
      MovieStar("Penélope Cruz"),
      MovieStar("Russell Crowe"),
      MovieStar("Marion Cotillard"),
      MovieStar("Forest Whitaker"),
      MovieStar("Halle Berry"),
      MovieStar("Idris Elba"),
      MovieStar("Octavia Spencer"),
      MovieStar("Mahershala Ali"),
      MovieStar("Tessa Thompson"),
      MovieStar("Oscar Isaac"),
      MovieStar("Margot Robbie"),
      MovieStar("Riz Ahmed"),
      MovieStar("Florence Pugh"),
      MovieStar("Adam Driver"),
      MovieStar("Zendaya"),
      MovieStar("Timothée Chalamet"),
      MovieStar("Awkwafina"),
      MovieStar("Michael B. Jordan"),
      MovieStar("Greta Gerwig"),
      MovieStar("Andrew Garfield"),
      MovieStar("Olivia Colman"),
      MovieStar("John Boyega"),
      MovieStar("Rachel Weisz"),
    )
  }
}

data class Movie(val title: String) {
  companion object {
    val all = listOf(
      Movie("The Godfather"),
      Movie("Casablanca"),
      Movie("Citizen Kane"),
      Movie("Schindler's List"),
      Movie("Pulp Fiction"),
      Movie("The Shawshank Redemption"),
      Movie("Forrest Gump"),
      Movie("Goodfellas"),
      Movie("The Dark Knight"),
      Movie("Fight Club"),
      Movie("Inception"),
      Movie("The Matrix"),
      Movie("Gladiator"),
      Movie("Titanic"),
      Movie("Jaws"),
      Movie("Star Wars"),
      Movie("Apocalypse Now"),
      Movie("Taxi Driver"),
      Movie("Raging Bull"),
      Movie("Vertigo"),
      Movie("Psycho"),
      Movie("Rear Window"),
      Movie("Singin' in the Rain"),
      Movie("Lawrence of Arabia"),
      Movie("2001: A Space Odyssey"),
      Movie("The Silence of the Lambs"),
      Movie("Saving Private Ryan"),
      Movie("Braveheart"),
      Movie("The Lord of the Rings"),
      Movie("The Departed"),
      Movie("There Will Be Blood"),
      Movie("No Country for Old Men"),
      Movie("Parasite"),
      Movie("Mad Max: Fury Road"),
      Movie("Whiplash"),
      Movie("La La Land"),
      Movie("Moonlight"),
      Movie("Get Out"),
      Movie("Birdman"),
      Movie("12 Years a Slave"),
      Movie("Spotlight"),
      Movie("The Revenant"),
      Movie("Manchester by the Sea"),
      Movie("Roma"),
      Movie("Joker"),
      Movie("Nomadland"),
      Movie("Everything Everywhere All at Once"),
      Movie("Oppenheimer"),
      Movie("Past Lives"),
      Movie("The Brutalist"),
      Movie("Anora"),
      Movie("Dune"),
      Movie("Killers of the Flower Moon"),
      Movie("Poor Things"),
      Movie("The Banshees of Inisherin"),
      Movie("Drive"),
      Movie("Arrival"),
      Movie("Her"),
      Movie("Eternal Sunshine of the Spotless Mind"),
      Movie("Lost in Translation"),
    )
  }
}

data class MovieRole(val name: String) {
  companion object {
    val all = listOf(
      MovieRole("Vito Corleone"),
      MovieRole("Michael Corleone"),
      MovieRole("Rick Blaine"),
      MovieRole("Ilsa Lund"),
      MovieRole("Charles Foster Kane"),
      MovieRole("Oskar Schindler"),
      MovieRole("Vincent Vega"),
      MovieRole("Jules Winnfield"),
      MovieRole("Andy Dufresne"),
      MovieRole("Ellis Boyd 'Red' Redding"),
      MovieRole("Forrest Gump"),
      MovieRole("Henry Hill"),
      MovieRole("Bruce Wayne"),
      MovieRole("The Joker"),
      MovieRole("Tyler Durden"),
      MovieRole("Dom Cobb"),
      MovieRole("Neo"),
      MovieRole("Trinity"),
      MovieRole("Maximus Decimus Meridius"),
      MovieRole("Jack Dawson"),
      MovieRole("Rose DeWitt Bukater"),
      MovieRole("Captain Quint"),
      MovieRole("Luke Skywalker"),
      MovieRole("Princess Leia"),
      MovieRole("Han Solo"),
      MovieRole("Darth Vader"),
      MovieRole("Captain Willard"),
      MovieRole("Colonel Kurtz"),
      MovieRole("Travis Bickle"),
      MovieRole("Jake LaMotta"),
      MovieRole("Norman Bates"),
      MovieRole("Hannibal Lecter"),
      MovieRole("Clarice Starling"),
      MovieRole("Captain John Miller"),
      MovieRole("William Wallace"),
      MovieRole("Frodo Baggins"),
      MovieRole("Aragorn"),
      MovieRole("Gandalf"),
      MovieRole("Daniel Plainview"),
      MovieRole("Anton Chigurh"),
      MovieRole("Kim Ki-taek"),
      MovieRole("Imperator Furiosa"),
      MovieRole("Mia Dolan"),
      MovieRole("Sebastian Wilder"),
      MovieRole("Chiron"),
      MovieRole("Chris Washington"),
      MovieRole("Riggan Thomson"),
      MovieRole("Solomon Northup"),
      MovieRole("Hugh Glass"),
      MovieRole("Lee Chandler"),
      MovieRole("Cleo"),
      MovieRole("Arthur Fleck"),
      MovieRole("Fern"),
      MovieRole("Evelyn Quan Wang"),
      MovieRole("J. Robert Oppenheimer"),
      MovieRole("Nora Moon"),
      MovieRole("László Tóth"),
      MovieRole("Anora Mikheeva"),
      MovieRole("Paul Atreides"),
      MovieRole("Lady Jessica"),
      MovieRole("Ernest Burkhart"),
      MovieRole("Bella Baxter"),
      MovieRole("Padraic Suilleabhain"),
      MovieRole("Driver"),
      MovieRole("Louise Banks"),
      MovieRole("Theodore Twombly"),
      MovieRole("Joel Barish"),
      MovieRole("Charlotte"),
    )
  }
}

data class MovieStarRole(val star: MovieStar, val movie: Movie, val role: MovieRole)

fun Arb.Companion.movieStar() = arbitrary { MovieStar.all.random(it.random) }
fun Arb.Companion.movie() = arbitrary { Movie.all.random(it.random) }
fun Arb.Companion.movieRole() = arbitrary { MovieRole.all.random(it.random) }

fun Arb.Companion.movieStarRole() =
  movieStar().flatMap { star ->
    movie().flatMap { movie ->
      movieRole().map { role -> MovieStarRole(star, movie, role) }
    }
  }
