name: release
run-name: release ${{ inputs.version }} from ${{ inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true
      branch:
        description: "The branch to release from"
        required: true
        default: 'master'

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  RELEASE_VERSION: ${{ inputs.version }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
  NEW_MAVEN_CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  NEW_MAVEN_CENTRAL_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: deploy to central portal
        run: ./gradlew publishAllPublicationsToCentralPortal
